name: Update casks from upstream releases

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update cask
        uses: Homebrew/actions/bump-casks@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          casks: siyuan-unlock
          tap: hluglk/homebrew-soft
          livecheck: true